config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORIES = %w(chinese italian japanese french belgian)

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, except: [:destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @reviw.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsYelpMvp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container mt-3">
    <div class="row">
      <div class="col-md-6 offset-md-3 py-5">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category, collection: Restaurant::CATEGORIES %>
<%= f.submit restaurant.persisted? ? 'Update' : 'Create' %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'restaurants/form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1 class=" d-flex justify-content-center mb-4">Restaurants</h1>

<ul class="list-group">
  <% @restaurants.each do |restaurant| %>
    <li class="list-group-item rounded-pill mb-1"><%= link_to restaurant.name, restaurant_path(restaurant), class: 'restaurant-name' %></li>
  <% end %>
</ul>

<%= link_to 'Create', new_restaurant_path, class: 'btn btn-outline-primary w-100 rounded-pill p-3 mt-4' %>

app/views/restaurants/new.html.erb
<h1>Create Restaurant</h1>

<%= render 'restaurants/form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %> details</h1>

<p>Address: <%= @restaurant.address %></p>
<p>Phone: <%= @restaurant.phone_number %></p>
<p>Category: <%= @restaurant.category %></p>

<% @restaurant.reviews.each do |review| %>
<p><%= review.content %></p>
<p><%= '⭐️' * review.rating %></p>
<hr>
<% end %>

<div class="row">
  <div class="col">
    <%= link_to 'Review', new_restaurant_review_path(@restaurant), class: 'btn btn-outline-primary w-100 rounded-pill p-3 mt-4' %>
  </div>
  <div class="col">
    <%= link_to 'Back', restaurants_path, class: 'btn btn-outline-success w-100 rounded-pill p-3 mt-4' %>
  </div>
  <div class="col">
    <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: 'btn btn-outline-info w-100 rounded-pill p-3 mt-4' %>
  </div>
  <div class="col">
    <%= link_to 'Delete', restaurant_path(@restaurant), class: 'btn btn-outline-danger w-100 rounded-pill p-3 mt-4', method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/reviews/new.html.erb
 <h1 class=" d-flex justify-content-center mb-4">Review Create</h1>

 <%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit class: 'btn-outline-primary' %>
<% end %>